### ISSUE TITLE
Innoextract extraction not working

### ISSUE THREAD

**Issue by vv221** [yancharkin/gogiunpack#1]
I tried your script on Linux, with innoextract.

I can see the data extraction process, that seems to go well, but something about un-obfuscating the files probably go wrong because at the end I get an empty folder where the extracted game data should be.

Is there any way to run the script with debug output, so I can post something here that would help you track the issue at hand?

-----

EDIT: I used the vanilla version of innoextract, having not noticed your fork. I’m going to try again with your fork and report back gere.

**Comment by yancharkin** [comment]
You need [this version of innoextact](https://github.com/yancharkin/innoextract) (as said in readme)

**Comment by vv221** [comment]
Right, with your fork everything went as is should ;)

Maybe a check using 'innoextract -v' before processing the installer would avoid other distracted people like me thinking that your script is faulty?

Anyway, I’m closing this bug report, sorry for the noise.
